version: '3.9'

services:
  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - 6379:6379

  # flask:
  #   build: .
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis

worker:
    build: ./worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./worker/worker.py:/app/worker.py

app:
  build: ./app
  volumes:
    - ./worker/worker.py:/app/worker.py
  ports:
    - 5050:5050
  environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - CELERY_RESULT_BACKEND=redis://redis:6379/0
  depends_on:
    - redis
    - worker

